name: dreamfusion
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.7
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - numpy
  - pip:
      - torch-ema
      - ninja
      - trimesh
      - opencv-python
      - tensorboardX
      - pandas
      - tqdm
      - matplotlib
      - PyMCubes
      - rich
      - dearpygui
      - scipy
      - huggingface_hub
      - diffusers >= 0.9.0 # for stable-diffusion 2.0
      - transformers
      - xatlas
      - scikit-learn
      - imageio
      - imageio-ffmpeg
      - accelerate
      - tensorboard
      - pymeshlab
      - git+https://github.com/NVlabs/nvdiffrast/
      - git+https://github.com/openai/CLIP.git
      - -e .