name: magic3d
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - cudatoolkit=11.3
  - pytorch=1.12.0
  - torchvision=0.13.0
  - torchaudio=0.12.0
  - numpy=1.19.2
  - pip:
      - selenium
      - pytorch-lightning==1.8.6
      - torch-ema
      - ninja
      - trimesh
      - opencv-python
      - tensorboardX
      - pandas
      - tqdm
      - matplotlib
      - PyMCubes
      - rich
      - dearpygui
      - scipy
      - huggingface_hub
      - diffusers >= 0.9.0 # for stable-diffusion 2.0
      - transformers
      - xatlas
      - scikit-learn
      - imageio
      - imageio-ffmpeg
      - accelerate
      - tensorboard
      - pymeshlab
      - einops==0.3.0
      - omegaconf==2.1.1
      - git+https://github.com/NVlabs/nvdiffrast/
      - git+https://github.com/openai/CLIP.git
      - -e .