module:
  target: models.magic3d.Magic3D
  params:
    nerf_config:
      target: models.nerf.nerf.InstantNGP
      params:
        bound: 1
    diffusion_config:
      target: models.diffusion.DiffusionWrapper
      params:
        grad_scale: 1.0
    prompt: "none"

data:
  target: datasets.util.DataModuleFromConfig
  params:
    batch_size: 1
    wrap: True
    train:
      target: datasets.base.NeRFTrainDataset
      params:
        near: 0.01
logger:
  target: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  params:
    save_dir: './logs'
    name: 'holoVAE'

checkpoints:
  latest_checkpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoint/holoVAE'
      filename: 'landscape_256_phases_19.5_mm_green'
      monitor: 'step'
      mode: 'max'
      save_top_k: 1