module:
  target: models.magic3d.Magic3D
  params:
    nerf_config:
      target: models.nerf.InstantNGP
      params:
        encoder_config:
          target: gridencoder.GridEncoder
          params:
            input_dim: 3
            num_levels: 16
            level_dim: 2
            base_resolution: 16
            log2_hashmap_size: 19
            desired_resolution: 2048
            align_corners: False
            interpolation: 'smoothstep'

        encoder_bg_config:
          target: freqencoder.FreqEncoder
          params:
            input_dim: 3
            degree: 6
        bound: 1

    diffusion_config:
      target: models.diffusion.DiffusionWrapper
      params:
        grad_scale: 1.0

    prompt: "none"

data:
  target: datasets.util.DataModuleFromConfig
  params:
    batch_size: 1
    wrap: True
    train:
      target: datasets.base.NeRFDataset
      params:
        near: 0.01
        H: 64
        W: 64
        train: True
    test:
      target: datasets.base.NeRFDataset
      params:
        H: 64
        W: 64
        train: false

logger:
  target: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  params:
    save_dir: './logs'
    name: 'first_stage/'

checkpoints:
  latest_checkpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoint/holoVAE'
      filename: 'landscape_256_phases_19.5_mm_green'
      monitor: 'step'
      mode: 'max'
      save_top_k: 1