module:
  target: models.maigc3d.Magic3D
  params:
    text: a
    negative: 0
    guidance: a
    seed: a
    guidance_scale: a
    mcubes_resolution: a
    decimate_target: a
    lr: 1e-3
    max_steps: 1024
    num_steps: 64
    upsameple_steps: 64
    update_extra_interval: 16
    max_ray_batch: 4096
    latent_iter_ratio: 0.2
    albedo_iter_ratio: 0
    min_ambient_ratio: 0.2
    jitter_pose: False
    jitter_center: 0.2
    jitter_target: 0.2
    jitter_up: 0.02
    uniform_sphere_rate: 0
    grad_clip: -1
    grad_clip_rgb: -1

    bg_radius: 1.4
    density_activation: exp
    density_thresh: 10
    blob_density: 5
    blob_radius: 0.2

    nerf_config:
      w: 64
      h: 64
      known_view_scale: 1.5
      known_view_noise_scale: 2e-3

    diffusion_config:
      fp16: False
      vram: False

    gui_config:
      gui: false
      W: 800
      H: 800
      radius: 3
      fovy: 60
      light_theta: 60
      light_phi: 0
      mas_spp: 1

data:
  target: dataset.util.DataModuleFromConfig
  params:
    num_workers: 4
    batch_size: 1
    wrap: True
    train:
      target: dataset.Base
      params:
        data_path: '../data/landscape128'
        format: '.png'
        channel: 1
        image_res: [256, 256]
        homography_res: [128, 128]
        vertical_flips: True
        horizontal_flips: True

logger:
  target: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  params:
    save_dir: './logs'
    name: 'holoVAE'

checkpoints:
  val_checkpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoint/holoVAE'
      filename: 'landscape_256_phases_19.5_mm_green_best_loss'
      monitor: 'Loss'
      mode: 'min'
      save_top_k: 1

  latest_checkpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoint/holoVAE'
      filename: 'landscape_256_phases_19.5_mm_green'
      monitor: 'step'
      mode: 'max'
      save_top_k: 1